"""Add headline to profileinfo

Revision ID: 30baa21259bf
Revises: ff25a21df236
Create Date: 2025-08-04 09:06:16.399887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '30baa21259bf'
down_revision: Union[str, Sequence[str], None] = 'ff25a21df236'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profileinfo', sa.Column('headline', sa.VARCHAR(length=255), nullable=True))
    op.add_column('profileinfo', sa.Column('profile_image_id', sa.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profileinfo', 'profile_image_id')
    op.drop_column('profileinfo', 'headline')
    # ### end Alembic commands ###
