"""portfolio models added

Revision ID: 5a7f1d920ae4
Revises: a6bac8da1157
Create Date: 2025-08-01 16:47:57.919970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '5a7f1d920ae4'
down_revision: Union[str, Sequence[str], None] = 'a6bac8da1157'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('education',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school', sa.VARCHAR(length=100), nullable=False),
    sa.Column('degree', sa.VARCHAR(length=100), nullable=False),
    sa.Column('start_year', sa.INTEGER(), nullable=False),
    sa.Column('end_year', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profileinfo',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('about', sa.TEXT(), nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=15), nullable=True),
    sa.Column('location', sa.VARCHAR(length=100), nullable=True),
    sa.Column('github_url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('linkedin_url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('resume_url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('instagram', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('skill',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), nullable=False),
    sa.Column('image_link', sa.VARCHAR(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('workexperience',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company', sa.VARCHAR(length=100), nullable=False),
    sa.Column('position', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), nullable=False),
    sa.Column('start_date', sa.DATE(), nullable=False),
    sa.Column('end_date', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workexperience')
    op.drop_table('skill')
    op.drop_table('profileinfo')
    op.drop_table('education')
    # ### end Alembic commands ###
