"""init

Revision ID: 80cf57079ccf
Revises: 
Create Date: 2025-09-04 18:24:29.606600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '80cf57079ccf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accessleveltag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accessleveltag_name'), 'accessleveltag', ['name'], unique=True)
    op.create_table('education',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school', sa.VARCHAR(length=100), nullable=False),
    sa.Column('degree', sa.VARCHAR(length=100), nullable=False),
    sa.Column('start_year', sa.INTEGER(), nullable=False),
    sa.Column('end_year', sa.INTEGER(), nullable=False),
    sa.Column('Score', sa.FLOAT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profileinfo',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('about', sa.TEXT(), nullable=True),
    sa.Column('headline', sa.VARCHAR(length=255), nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=15), nullable=True),
    sa.Column('location', sa.VARCHAR(length=100), nullable=True),
    sa.Column('github_url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('linkedin_url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('resume_file_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('instagram', sa.VARCHAR(length=255), nullable=True),
    sa.Column('profile_image_id', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('short_description', sa.TEXT(), nullable=False),
    sa.Column('long_description', sa.TEXT(), nullable=False),
    sa.Column('access_level', postgresql.ENUM('PUBLIC', 'ADMIN', 'LOGGED_IN_USERS', 'SPECIAL_ACCESS_USERS', 'NOT_LIVE', 'SUPERADMIN', name='accesslevel'), nullable=False),
    sa.Column('skills_used', postgresql.ARRAY(sa.VARCHAR()), nullable=True),
    sa.Column('github_link_backend', sa.VARCHAR(length=255), nullable=True),
    sa.Column('github_link_frontend', sa.VARCHAR(length=255), nullable=True),
    sa.Column('ngrok_url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('is_interesting_project', sa.BOOLEAN(), nullable=False),
    sa.Column('is_live', sa.BOOLEAN(), nullable=False),
    sa.Column('docker_image_link_backend', sa.VARCHAR(length=255), nullable=True),
    sa.Column('docker_image_link_frontend', sa.VARCHAR(length=255), nullable=True),
    sa.Column('contributors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roletag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roletag_name'), 'roletag', ['name'], unique=True)
    op.create_table('skillcategory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('preferred_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), nullable=False),
    sa.Column('role', postgresql.ENUM('USER', 'ADMIN', 'SUBADMIN', 'FAMILY', 'SPECIAL_USER', name='userrole'), nullable=False),
    sa.Column('email_verified', sa.BOOLEAN(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('preferred_name')
    )
    op.create_table('workexperience',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company', sa.VARCHAR(length=100), nullable=False),
    sa.Column('position', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.JSON(), nullable=True),
    sa.Column('start_date', sa.DATE(), nullable=False),
    sa.Column('end_date', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projectmembership',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'project_id')
    )
    op.create_table('skill',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('image_id', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['skillcategory.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_skill_category_id'), 'skill', ['category_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skill_category_id'), table_name='skill')
    op.drop_table('skill')
    op.drop_table('projectmembership')
    op.drop_table('workexperience')
    op.drop_table('users')
    op.drop_table('skillcategory')
    op.drop_index(op.f('ix_roletag_name'), table_name='roletag')
    op.drop_table('roletag')
    op.drop_table('projects')
    op.drop_table('profileinfo')
    op.drop_table('education')
    op.drop_index(op.f('ix_accessleveltag_name'), table_name='accessleveltag')
    op.drop_table('accessleveltag')
    # ### end Alembic commands ###
