"""added sequence field in education and work exp

Revision ID: 9811e03e045d
Revises: cbeb31dcbf23
Create Date: 2025-10-19 14:08:03.636471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '9811e03e045d'
down_revision: Union[str, Sequence[str], None] = 'cbeb31dcbf23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('education', sa.Column('sequence', sa.INTEGER(), nullable=False))
    op.add_column('workexperience', sa.Column('sequence', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workexperience', 'sequence')
    op.drop_column('education', 'sequence')
    # ### end Alembic commands ###
