"""initial schema

Revision ID: a6bac8da1157
Revises: 
Create Date: 2025-08-01 15:25:11.990507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'a6bac8da1157'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accessleveltag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accessleveltag_name'), 'accessleveltag', ['name'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('short_description', sa.TEXT(), nullable=False),
    sa.Column('long_description', sa.TEXT(), nullable=False),
    sa.Column('access_level', postgresql.ENUM('PUBLIC', 'ADMIN', 'LOGGED_IN_USERS', 'SPECIAL_ACCESS_USERS', 'NOT_LIVE', name='accesslevel'), nullable=False),
    sa.Column('skills_used', postgresql.ARRAY(sa.VARCHAR()), nullable=True),
    sa.Column('github_link_backend', sa.VARCHAR(length=255), nullable=True),
    sa.Column('github_link_frontend', sa.VARCHAR(length=255), nullable=True),
    sa.Column('ngrok_url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('is_interesting_project', sa.BOOLEAN(), nullable=False),
    sa.Column('is_live', sa.BOOLEAN(), nullable=False),
    sa.Column('docker_image_link_backend', sa.VARCHAR(length=255), nullable=True),
    sa.Column('docker_image_link_frontend', sa.VARCHAR(length=255), nullable=True),
    sa.Column('contributors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roletag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roletag_name'), 'roletag', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('preferred_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), nullable=False),
    sa.Column('role', postgresql.ENUM('USER', 'ADMIN', 'SUBADMIN', 'FAMILY', 'SPECIAL_USER', name='userrole'), nullable=False),
    sa.Column('email_verified', sa.BOOLEAN(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('preferred_name')
    )
    op.create_table('projectmembership',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'project_id')
    )
    op.create_index(op.f('ix_projectmembership_project_id'), 'projectmembership', ['project_id'], unique=False)
    op.create_index(op.f('ix_projectmembership_user_id'), 'projectmembership', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projectmembership_user_id'), table_name='projectmembership')
    op.drop_index(op.f('ix_projectmembership_project_id'), table_name='projectmembership')
    op.drop_table('projectmembership')
    op.drop_table('users')
    op.drop_index(op.f('ix_roletag_name'), table_name='roletag')
    op.drop_table('roletag')
    op.drop_table('projects')
    op.drop_index(op.f('ix_accessleveltag_name'), table_name='accessleveltag')
    op.drop_table('accessleveltag')
    # ### end Alembic commands ###
