"""Add headline to profileinfo

Revision ID: c81245d35e4f
Revises: 30baa21259bf
Create Date: 2025-08-06 06:30:10.914286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'c81245d35e4f'
down_revision: Union[str, Sequence[str], None] = '30baa21259bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skill', sa.Column('image_id', sa.VARCHAR(length=255), nullable=True))
    op.drop_column('skill', 'image_link')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skill', sa.Column('image_link', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.drop_column('skill', 'image_id')
    # ### end Alembic commands ###
