"""prefered name in the user model can now be same as well

Revision ID: d654541e6872
Revises: 9811e03e045d
Create Date: 2025-10-23 09:24:10.104881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'd654541e6872'
down_revision: Union[str, Sequence[str], None] = '9811e03e045d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_preferred_name_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_preferred_name_key'), 'users', ['preferred_name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
