"""make education end_year and workexperience end_date nullable

Revision ID: d672cf710491
Revises: d654541e6872
Create Date: 2025-12-02 16:06:28.506276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'd672cf710491'
down_revision: Union[str, Sequence[str], None] = 'd654541e6872'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('education', 'end_year',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_preferred_name'), 'users', ['preferred_name'], unique=False)
    op.alter_column('workexperience', 'end_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workexperience', 'end_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_index(op.f('ix_users_preferred_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('education', 'end_year',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
