"""portfolio models added

Revision ID: ff25a21df236
Revises: 6aedab95bb88
Create Date: 2025-08-01 17:11:40.904517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'ff25a21df236'
down_revision: Union[str, Sequence[str], None] = '6aedab95bb88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('education', sa.Column('Score', sa.FLOAT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('education', 'Score')
    # ### end Alembic commands ###
